import { z } from 'zod';
import type { IntakeDefinition, Section, SelectOption } from './types';
import {
  buildSectionSchemas,
  emailSchema,
  longText,
  optionalText,
  requiredText,
  slider,
  telSchema,
  websiteSchema,
} from './_shared';

const typeStyles: SelectOption[] = [
  { label: 'Serif (classic, editorial)', value: 'serif' },
  { label: 'Sans-serif (clean, modern)', value: 'sans' },
  { label: 'Geometric sans (architectural)', value: 'geometric-sans' },
  { label: 'Display or decorative', value: 'display' },
  { label: 'Slab serif (sturdy, confident)', value: 'slab' },
  { label: 'Hand-drawn or script', value: 'script' },
  { label: 'Monospace or technical', value: 'mono' },
  { label: 'Editorial / magazine', value: 'editorial' },
];

const logoTypes: SelectOption[] = [
  { label: 'Wordmark (just the name in a custom typeface)', value: 'wordmark' },
  { label: 'Symbol or icon only', value: 'symbol' },
  { label: 'Both — wordmark plus a mark', value: 'both' },
  { label: 'Not sure yet, you decide', value: 'undecided' },
];

const startingPoint: SelectOption[] = [
  { label: 'Starting completely fresh', value: 'fresh' },
  { label: 'Evolving an existing logo', value: 'evolve' },
  { label: 'Open to either, depending on what you recommend', value: 'open' },
];

const usageContexts: SelectOption[] = [
  { label: 'Website and digital', value: 'web' },
  { label: 'Social media profile photo', value: 'social' },
  { label: 'Print collateral (cards, flyers, brochures)', value: 'print' },
  { label: 'Signage', value: 'signage' },
  { label: 'Apparel or merchandise', value: 'apparel' },
  { label: 'Vehicle wraps', value: 'vehicles' },
  { label: 'Packaging', value: 'packaging' },
  { label: 'App icon', value: 'app-icon' },
  { label: 'Embroidery or stitched applications', value: 'embroidery' },
];

const sections: Section[] = [
  {
    id: 'basics',
    index: 1,
    title: 'The Basics',
    intro: "Let's start with who I'm working with. This part is quick.",
    questions: [
      { id: 'business_name', number: 1, label: 'Business name', kind: 'text', required: true, autoComplete: 'organization' },
      { id: 'contact_name', number: 2, label: 'Your name', kind: 'text', required: true, autoComplete: 'name' },
      { id: 'contact_email', number: 3, label: 'Email address', kind: 'email', required: true, autoComplete: 'email' },
      { id: 'contact_phone', number: 4, label: 'Phone number', kind: 'tel', required: false, autoComplete: 'tel' },
      {
        id: 'website_url',
        number: 5,
        label: 'Website',
        helper: 'Domain or full URL is fine. No need to include https://.',
        kind: 'text',
        required: false,
        placeholder: 'mycreativestrategist.com',
        autoComplete: 'url',
        hideWhen: 'no_website',
      },
      {
        id: 'no_website',
        label: 'I don’t have a website yet',
        kind: 'boolean',
        required: false,
      },
      { id: 'industry', number: 6, label: 'Industry or category', kind: 'text', required: true, autoComplete: 'off' },
    ],
  },
  {
    id: 'essence',
    index: 2,
    title: 'Brand Essence',
    intro: "The thing we're translating into a visual identity. Don't overthink it. Plain language always beats marketing speak.",
    questions: [
      {
        id: 'what_you_do',
        number: 7,
        label: 'In plain language, what does your business actually do?',
        helper: 'Imagine you’re telling a smart friend at dinner.',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'who_for',
        number: 8,
        label: 'Who is this brand for?',
        helper: 'A short paragraph on your ideal customer is enough.',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'first_feeling',
        number: 9,
        label: 'When someone sees your brand for the first time, what should they feel?',
        helper: 'One sentence is great. "Calm and confident." "Like they finally found the right one."',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'one_sentence_message',
        number: 10,
        label: 'If your brand could only say one thing to the world, what would it be?',
        kind: 'longtext',
        required: false,
      },
    ],
  },
  {
    id: 'personality',
    index: 3,
    title: 'Personality',
    intro: 'If your brand walked into a room, who would it be?',
    questions: [
      { id: 'adjectives_yes', number: 11, label: 'Five adjectives that describe your brand', helper: 'Comma separated.', kind: 'text', required: true },
      { id: 'adjectives_no', number: 12, label: 'Five adjectives your brand should never be', helper: 'Comma separated.', kind: 'text', required: true },
      { id: 'brand_as_person', number: 13, label: 'If your brand were a person, who would they be? Real or fictional, both fine.', kind: 'longtext', required: true },
      { id: 'tone_formal_casual', number: 14, label: 'Tone: very formal to very casual', kind: 'slider', required: true, min: 1, max: 10, step: 1, minLabel: 'Very formal', maxLabel: 'Very casual' },
      { id: 'tone_understated_bold', number: 15, label: 'Tone: understated to bold', kind: 'slider', required: true, min: 1, max: 10, step: 1, minLabel: 'Understated', maxLabel: 'Bold' },
      { id: 'tone_classic_modern', number: 16, label: 'Aesthetic: classic to modern', kind: 'slider', required: true, min: 1, max: 10, step: 1, minLabel: 'Classic', maxLabel: 'Modern' },
    ],
  },
  {
    id: 'color',
    index: 4,
    title: 'Color Direction',
    intro: 'Be specific. The more concrete you are, the closer the first round will land.',
    questions: [
      {
        id: 'current_colors',
        number: 17,
        label: 'Current brand colors, if you have any',
        helper: 'Hex codes if you know them, otherwise just describe.',
        kind: 'longtext',
        required: false,
      },
      {
        id: 'colors_love',
        number: 18,
        label: 'Colors you love',
        helper: 'They don’t have to be "for the brand" yet. Just colors that pull at you.',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'colors_represent',
        number: 19,
        label: 'Colors that feel like *you* or this business specifically',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'colors_avoid',
        number: 20,
        label: 'Colors you absolutely don’t want anywhere near this brand',
        kind: 'longtext',
        required: false,
      },
      { id: 'mood_warm_cool', number: 21, label: 'Color mood: warm to cool', kind: 'slider', required: true, min: 1, max: 10, step: 1, minLabel: 'Warm', maxLabel: 'Cool' },
      { id: 'mood_light_dark', number: 22, label: 'Color mood: light to dark', kind: 'slider', required: true, min: 1, max: 10, step: 1, minLabel: 'Light', maxLabel: 'Dark' },
      { id: 'mood_muted_saturated', number: 23, label: 'Color mood: muted to saturated', kind: 'slider', required: true, min: 1, max: 10, step: 1, minLabel: 'Muted', maxLabel: 'Saturated' },
    ],
  },
  {
    id: 'typography',
    index: 5,
    title: 'Typography',
    intro: 'Type carries half the personality. Tell me what feels right.',
    questions: [
      {
        id: 'type_styles',
        number: 24,
        label: 'Type styles that draw you in',
        helper: 'Pick all that apply.',
        kind: 'multiselect',
        required: true,
        options: typeStyles,
      },
      {
        id: 'fonts_loved',
        number: 25,
        label: 'Specific fonts you love, if you know names',
        helper: 'Optional. Things like Inter, Söhne, Caslon, Recoleta — anything you’ve noticed in the wild.',
        kind: 'longtext',
        required: false,
      },
      {
        id: 'typography_words',
        number: 26,
        label: 'Words that describe the typography feel you want',
        helper: 'Examples: editorial, friendly, technical, soft, architectural, hand-made.',
        kind: 'longtext',
        required: false,
      },
    ],
  },
  {
    id: 'references',
    index: 6,
    title: 'Visual References',
    intro: 'This section gives me the most signal. Be specific. Vague references give vague results.',
    questions: [
      {
        id: 'brands_loved',
        number: 27,
        label: 'Three brands you love, with links if possible',
        helper: 'Add a sentence on *why* each one. The why matters more than the what.',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'websites_loved',
        number: 28,
        label: 'Three websites you love and what makes them work for you',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'logos_admired',
        number: 29,
        label: 'Logos you admire, and a sentence on why',
        kind: 'longtext',
        required: false,
      },
      {
        id: 'avoid_visual',
        number: 30,
        label: 'Anything you definitely don’t want it to look like',
        helper: 'Brands, styles, eras, anything to steer clear of.',
        kind: 'longtext',
        required: false,
      },
    ],
  },
  {
    id: 'logo_specifics',
    index: 7,
    title: 'Logo Specifics',
    intro: 'The practical decisions that shape what I design.',
    questions: [
      {
        id: 'name_meaning',
        number: 31,
        label: 'What does the brand name mean to you?',
        helper: 'Backstory, an association, what you want it to evoke. Anything helps.',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'logo_type',
        number: 32,
        label: 'What kind of logo are you imagining?',
        kind: 'select',
        required: true,
        options: logoTypes,
      },
      {
        id: 'starting_point',
        number: 33,
        label: 'Are we starting fresh, or evolving something?',
        kind: 'select',
        required: true,
        options: startingPoint,
      },
      {
        id: 'usage_contexts',
        number: 34,
        label: 'Where does this logo absolutely need to work?',
        helper: 'Pick all that apply. Constraints I should know about up front.',
        kind: 'multiselect',
        required: true,
        options: usageContexts,
      },
      {
        id: 'color_modes',
        number: 35,
        label: 'Will this need to work in single color or print on one ink anywhere?',
        helper: 'Embroidery, etching, single-color print, dark backgrounds — anything specific.',
        kind: 'longtext',
        required: false,
      },
    ],
  },
  {
    id: 'logistics',
    index: 8,
    title: 'Logistics',
    intro: 'A few practicalities so we run a smooth project.',
    questions: [
      {
        id: 'timeline',
        number: 36,
        label: 'Desired launch or reveal date',
        helper: 'Even a rough quarter is helpful.',
        kind: 'text',
        required: true,
      },
      {
        id: 'approvers',
        number: 37,
        label: 'Who else is involved in approving creative decisions?',
        kind: 'longtext',
        required: true,
      },
      {
        id: 'anything_else',
        number: 38,
        label: 'Anything else I should know before we begin?',
        kind: 'longtext',
        required: false,
      },
    ],
  },
  {
    id: 'uploads',
    index: 9,
    title: 'Uploads',
    intro: "Last step. Send me anything visual that'll help me get up to speed.",
    questions: [
      {
        id: 'files_existing_logo',
        number: 39,
        label: 'Existing logo files, if any',
        helper: 'Vector files (.svg, .ai, .pdf) ideal, but anything is fine.',
        kind: 'upload',
        required: false,
        accept: ['.png', '.jpg', '.jpeg', '.svg', '.ai', '.pdf'],
        maxSizeMb: 25,
        maxFiles: 5,
        category: 'logo',
      },
      {
        id: 'files_inspiration',
        number: 40,
        label: 'Inspiration: moodboards, screenshots, photographs of things you love',
        helper: 'Up to ten files.',
        kind: 'upload',
        required: false,
        accept: ['.png', '.jpg', '.jpeg', '.pdf'],
        maxSizeMb: 50,
        maxFiles: 10,
        category: 'photography',
      },
      {
        id: 'files_other',
        number: 41,
        label: 'Anything else relevant',
        helper: 'Old logos to retire, swatches, pitch decks, photography, whatever.',
        kind: 'upload',
        required: false,
        accept: ['.pdf', '.docx', '.pptx', '.png', '.jpg', '.jpeg'],
        maxSizeMb: 100,
        maxFiles: 10,
        category: 'marketing_materials',
      },
    ],
  },
];

const responsesSchema = z.object({
  business_name: requiredText('Business name'),
  contact_name: requiredText('Your name'),
  contact_email: emailSchema,
  contact_phone: telSchema,
  website_url: websiteSchema,
  no_website: z.boolean().optional(),
  industry: requiredText('Industry or category'),

  what_you_do: longText('What your business does', true),
  who_for: longText('Who the brand is for', true),
  first_feeling: longText('First feeling', true),
  one_sentence_message: longText('One-sentence message', false),

  adjectives_yes: requiredText('Adjectives that describe your brand'),
  adjectives_no: requiredText('Adjectives your brand should never be'),
  brand_as_person: longText('Brand as a person', true),
  tone_formal_casual: slider,
  tone_understated_bold: slider,
  tone_classic_modern: slider,

  current_colors: optionalText,
  colors_love: longText('Colors you love', true),
  colors_represent: longText('Colors that represent you', true),
  colors_avoid: optionalText,
  mood_warm_cool: slider,
  mood_light_dark: slider,
  mood_muted_saturated: slider,

  type_styles: z.array(z.string()).min(1, 'Pick at least one'),
  fonts_loved: optionalText,
  typography_words: optionalText,

  brands_loved: longText('Brands you love', true),
  websites_loved: longText('Websites you love', true),
  logos_admired: longText('Logos admired', false),
  avoid_visual: longText('Visual styles to avoid', false),

  name_meaning: longText('What the brand name means', true),
  logo_type: z.enum(['wordmark', 'symbol', 'both', 'undecided']),
  starting_point: z.enum(['fresh', 'evolve', 'open']),
  usage_contexts: z.array(z.string()).min(1, 'Pick at least one'),
  color_modes: longText('Color mode constraints', false),

  timeline: requiredText('Desired timeline'),
  approvers: longText('Approvers', true),
  anything_else: longText('Anything else', false),
});

export const brandingIntake: IntakeDefinition = {
  kind: 'branding',
  label: 'Branding intake',
  slug: 'branding',
  description:
    'Focused intake for visual identity work. Logo, color, type, references. Use this when the engagement is brand design rather than full strategy.',
  estimatedMinutes: '15 to 25 minutes',
  sections,
  responsesSchema,
  sectionSchemas: buildSectionSchemas(sections, responsesSchema),
  fileCategoryLabels: {
    logo: 'Existing logo files',
    photography: 'Inspiration & references',
    marketing_materials: 'Other reference materials',
  },
  hero: {
    eyebrow: 'Branding intake',
    title: 'Let’s give your business a visual identity that actually fits.',
    body: [
      'This intake is built around the visual side of your brand: logo, color, type, and the references that point me in the right direction. Most clients finish in fifteen to twenty-five minutes, and you can save and come back any time.',
      'Be specific. The clearer you are with me here, the closer the first round of design will land.',
    ],
  },
};
